### ISSUE TITLE
Unnecessary parens

### ISSUE THREAD

**Issue by alexschneider** [rtoal/iki-compiler#2]
https://github.com/rtoal/iki-compiler/blob/master/parser.coffee#L169

https://github.com/rtoal/iki-compiler/blob/master/parser.coffee#L77

https://github.com/rtoal/iki-compiler/blob/master/parser.coffee#L86

https://github.com/rtoal/iki-compiler/blob/master/parser.coffee#L95

https://github.com/rtoal/iki-compiler/blob/master/parser.coffee#L97

https://github.com/rtoal/iki-compiler/blob/master/parser.coffee#L99

There's a couple others in the file that could be seen as unnecessary, but I can see why they may need to be left in. 

Other files:
https://github.com/rtoal/iki-compiler/blob/master/entities/whilestatement.coffee#L7

https://github.com/rtoal/iki-compiler/blob/master/entities/whilestatement.coffee#L15

https://github.com/rtoal/iki-compiler/blob/master/entities/block.coffee#L5

**Comment by rtoal** [comment]
Thanks, Alex!
